#!/usr/bin/env node
/**
 * scripts/build-index.mjs
 *
 * Regenerates the autogenerated section of reports/00-INDEX.md from each
 * report's YAML frontmatter. The hand-curated content after the
 * `<!-- END AUTOGENERATED -->` marker (Quick Reference table) is preserved.
 *
 *   node scripts/build-index.mjs
 *
 * CI runs this and fails the build if `git diff` is non-empty afterwards.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { wrapIndex, _resetCache } from "../server.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const indexPath = join(ROOT, "reports", "00-INDEX.md");

if (!existsSync(indexPath)) {
  console.error(`reports/00-INDEX.md not found at ${indexPath}`);
  process.exit(1);
}

_resetCache();
const raw = readFileSync(indexPath, "utf-8");
if (!raw.includes("<!-- BEGIN AUTOGENERATED") || !raw.includes("<!-- END AUTOGENERATED")) {
  console.error("reports/00-INDEX.md is missing <!-- BEGIN/END AUTOGENERATED --> markers.");
  console.error("Add them around the report-listing section to enable build-index.");
  process.exit(1);
}
const wrapped = wrapIndex(raw);
if (wrapped === raw) {
  console.log("Index already up to date.");
} else {
  writeFileSync(indexPath, wrapped);
  console.log("Regenerated reports/00-INDEX.md.");
}
